// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ValhallaVault.Data;

#nullable disable

namespace ValhallaVault.Migrations
{
    [DbContext(typeof(ProgramDbContext))]
    partial class ProgramDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ValhallaVault.Data.Models.AnswerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Implementera starka lösenord",
                            IsCorrect = true,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Answer = "Uppdatera programvara regelbundet",
                            IsCorrect = false,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 3,
                            Answer = "Dela personlig information på sociala medier",
                            IsCorrect = false,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 4,
                            Answer = "Aktivera tvåfaktorsautentisering",
                            IsCorrect = true,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 5,
                            Answer = "Använda offentliga Wi-Fi utan försiktighet",
                            IsCorrect = false,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 6,
                            Answer = "Lagra känslig information på osäkra enheter",
                            IsCorrect = false,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 7,
                            Answer = "Förhindrar obehörig åtkomst till data",
                            IsCorrect = true,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 8,
                            Answer = "Krypterar data under överföring",
                            IsCorrect = false,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 9,
                            Answer = "Minskar kostnaderna för datalagring",
                            IsCorrect = false,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 10,
                            Answer = "Använda säkra betalningsgatewayer",
                            IsCorrect = true,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 11,
                            Answer = "Dela lösenord med andra",
                            IsCorrect = false,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 12,
                            Answer = "Använda osäkra Wi-Fi-nätverk för transaktioner",
                            IsCorrect = false,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 13,
                            Answer = "Granska integritetsinställningar på sociala medieplattformar",
                            IsCorrect = true,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 14,
                            Answer = "Ladda ner programvara från okända källor",
                            IsCorrect = false,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 15,
                            Answer = "Använda samma lösenord för flera konton",
                            IsCorrect = false,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 16,
                            Answer = "Övervaka kreditrapporter för misstänksam aktivitet",
                            IsCorrect = true,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 17,
                            Answer = "Ignorera kreditrapporter",
                            IsCorrect = false,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 18,
                            Answer = "Dela kreditkortsuppgifter online",
                            IsCorrect = false,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 19,
                            Answer = "Tidig upptäckt av identitetsstöld",
                            IsCorrect = true,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 20,
                            Answer = "Utsätta personlig information på sociala medier",
                            IsCorrect = false,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 21,
                            Answer = "Undvika finansiella transaktioner",
                            IsCorrect = false,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 22,
                            Answer = "Kontrollera kreditrapporter regelbundet",
                            IsCorrect = true,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 23,
                            Answer = "Ignorera kreditkortsutdrag",
                            IsCorrect = false,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 24,
                            Answer = "Dela personlig information med okända personer",
                            IsCorrect = false,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 25,
                            Answer = "Rapportera till kreditbyråer",
                            IsCorrect = true,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 26,
                            Answer = "Ignorera misstänksam aktivitet",
                            IsCorrect = false,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 27,
                            Answer = "Dela kreditkortsuppgifter online",
                            IsCorrect = false,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 28,
                            Answer = "Använda identitetsskyddstjänster",
                            IsCorrect = true,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 29,
                            Answer = "Dela personlig information på sociala medier",
                            IsCorrect = false,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 30,
                            Answer = "Ignorera bedrägliga aktiviteter",
                            IsCorrect = false,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 31,
                            Answer = "Säkra anslutningar med kryptering",
                            IsCorrect = true,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 32,
                            Answer = "Dela personuppgifter på osäkra webbplatser",
                            IsCorrect = false,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 33,
                            Answer = "Ignorera indikatorer för webbplatsens säkerhet",
                            IsCorrect = false,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 34,
                            Answer = "Använda VPN för krypterade anslutningar",
                            IsCorrect = true,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 35,
                            Answer = "Dela personuppgifter på offentliga nätverk",
                            IsCorrect = false,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 36,
                            Answer = "Inaktivera brandväggsinställningar",
                            IsCorrect = false,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 37,
                            Answer = "Säkerställa att webbläsaruppdateringar är aktuella",
                            IsCorrect = true,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 38,
                            Answer = "Inaktivera webbläsaruppdateringar",
                            IsCorrect = false,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 39,
                            Answer = "Ignorera webbläsarsäkerhetsvarningar",
                            IsCorrect = false,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 40,
                            Answer = "Phishingattacker",
                            IsCorrect = true,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 41,
                            Answer = "Uppdatera programvara regelbundet",
                            IsCorrect = false,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 42,
                            Answer = "Använda starka lösenord",
                            IsCorrect = false,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 43,
                            Answer = "Kontrollera SSL-certifikat",
                            IsCorrect = true,
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 44,
                            Answer = "Lämna personlig information på vilken webbplats som helst",
                            IsCorrect = false,
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 45,
                            Answer = "Ignorera indikatorer för webbplatsens säkerhet",
                            IsCorrect = false,
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 46,
                            Answer = "Bedrägliga e-postmeddelanden som syftar till att få personlig information",
                            IsCorrect = true,
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 47,
                            Answer = "Legitima e-postmeddelanden från betrodda källor",
                            IsCorrect = false,
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 48,
                            Answer = "Ladda ner bilagor från okända avsändare",
                            IsCorrect = false,
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 49,
                            Answer = "Kontrollera avsändarens e-postadress för äkthet",
                            IsCorrect = true,
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 50,
                            Answer = "Klicka på misstänkta länkar i e-postmeddelanden",
                            IsCorrect = false,
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 51,
                            Answer = "Lämna personlig information som svar på e-postmeddelanden",
                            IsCorrect = false,
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 52,
                            Answer = "Felstavat avsändarens e-postadress",
                            IsCorrect = true,
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 53,
                            Answer = "Kontrollera endast ämnesraden på e-postmeddelanden",
                            IsCorrect = false,
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 54,
                            Answer = "Öppna alla bifogade filer i e-postmeddelanden",
                            IsCorrect = false,
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 55,
                            Answer = "För att undvika att lämna ut personlig information till bedragare",
                            IsCorrect = true,
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 56,
                            Answer = "För att ge mer information till avsändaren",
                            IsCorrect = false,
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 57,
                            Answer = "För att visa intresse för e-postmeddelandet",
                            IsCorrect = false,
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 58,
                            Answer = "Rapportera till lämpliga myndigheter eller organisationer",
                            IsCorrect = true,
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 59,
                            Answer = "Svara på e-postmeddelandet och fråga om mer information",
                            IsCorrect = false,
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 60,
                            Answer = "Ignorera e-postmeddelandet och radera det",
                            IsCorrect = false,
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 61,
                            Answer = "Genomföra regelbundna sårbarhetsskanningar",
                            IsCorrect = true,
                            QuestionId = 21
                        },
                        new
                        {
                            Id = 62,
                            Answer = "Uppgradera nätverksservrar",
                            IsCorrect = false,
                            QuestionId = 21
                        },
                        new
                        {
                            Id = 63,
                            Answer = "Implementera säkerhetsrevisioner",
                            IsCorrect = false,
                            QuestionId = 21
                        },
                        new
                        {
                            Id = 64,
                            Answer = "Definiera strategier för att hantera risker",
                            IsCorrect = true,
                            QuestionId = 22
                        },
                        new
                        {
                            Id = 65,
                            Answer = "Utvärdera konkurrenternas säkerhetsåtgärder",
                            IsCorrect = false,
                            QuestionId = 22
                        },
                        new
                        {
                            Id = 66,
                            Answer = "Skapa företagshemligheter",
                            IsCorrect = false,
                            QuestionId = 22
                        },
                        new
                        {
                            Id = 67,
                            Answer = "Använda uppdaterad antivirusprogramvara",
                            IsCorrect = true,
                            QuestionId = 23
                        },
                        new
                        {
                            Id = 68,
                            Answer = "Klicka på misstänkta länkar i e-postmeddelanden",
                            IsCorrect = false,
                            QuestionId = 23
                        },
                        new
                        {
                            Id = 69,
                            Answer = "Använda samma lösenord för alla konton",
                            IsCorrect = false,
                            QuestionId = 23
                        },
                        new
                        {
                            Id = 70,
                            Answer = "Skicka betalning om ransomware attackeras",
                            IsCorrect = true,
                            QuestionId = 24
                        },
                        new
                        {
                            Id = 71,
                            Answer = "Ignorera ransomware-meddelanden",
                            IsCorrect = false,
                            QuestionId = 24
                        },
                        new
                        {
                            Id = 72,
                            Answer = "Rapportera ransomware-attacken till myndigheterna",
                            IsCorrect = false,
                            QuestionId = 24
                        },
                        new
                        {
                            Id = 73,
                            Answer = "För att minska risken för dataintrång och bedrägerier",
                            IsCorrect = true,
                            QuestionId = 25
                        },
                        new
                        {
                            Id = 74,
                            Answer = "För att dela företagshemligheter med konkurrenter",
                            IsCorrect = false,
                            QuestionId = 25
                        },
                        new
                        {
                            Id = 75,
                            Answer = "För att öka antalet anställda inom företaget",
                            IsCorrect = false,
                            QuestionId = 25
                        },
                        new
                        {
                            Id = 76,
                            Answer = "Phishingattacker via e-post, skadlig programvara via nedladdningar, eller oavsiktlig dataexponering genom bristande säkerhetsmedvetenhet",
                            IsCorrect = true,
                            QuestionId = 26
                        },
                        new
                        {
                            Id = 77,
                            Answer = "Fysiskt intrång i företagets lokaler",
                            IsCorrect = false,
                            QuestionId = 26
                        },
                        new
                        {
                            Id = 78,
                            Answer = "Nätverksbaserade attacker mot konkurrenter",
                            IsCorrect = false,
                            QuestionId = 26
                        },
                        new
                        {
                            Id = 79,
                            Answer = "Genomföra cybersäkerhetsträning, skicka ut information om aktuella hot och bästa praxis regelbundet, och uppmuntra anställda att rapportera misstänkta aktiviteter",
                            IsCorrect = true,
                            QuestionId = 27
                        },
                        new
                        {
                            Id = 80,
                            Answer = "Ignorera säkerhetsmeddelanden från IT-avdelningen",
                            IsCorrect = false,
                            QuestionId = 27
                        },
                        new
                        {
                            Id = 81,
                            Answer = "Dela inloggningsuppgifter med externa parter",
                            IsCorrect = false,
                            QuestionId = 27
                        },
                        new
                        {
                            Id = 82,
                            Answer = "GDPR (Dataskyddsförordningen) och CCPA (California Consumer Privacy Act)",
                            IsCorrect = true,
                            QuestionId = 28
                        },
                        new
                        {
                            Id = 83,
                            Answer = "SOC 2 (Service Organization Control 2) och HIPAA (Health Insurance Portability and Accountability Act)",
                            IsCorrect = false,
                            QuestionId = 28
                        },
                        new
                        {
                            Id = 84,
                            Answer = "ISO 9001 (International Organization for Standardization) och PCI DSS (Payment Card Industry Data Security Standard)",
                            IsCorrect = false,
                            QuestionId = 28
                        },
                        new
                        {
                            Id = 85,
                            Answer = "Att de måste följa specifika regler och riktlinjer för att skydda användares personlig information, rapportera dataintrång och upprätthålla säkerhetsåtgärder för att förhindra obehörig åtkomst",
                            IsCorrect = true,
                            QuestionId = 29
                        },
                        new
                        {
                            Id = 86,
                            Answer = "Att de måste dela företagshemligheter med andra företag",
                            IsCorrect = false,
                            QuestionId = 29
                        },
                        new
                        {
                            Id = 87,
                            Answer = "Att de måste ignorera dataintrångsförsök från externa parter",
                            IsCorrect = false,
                            QuestionId = 29
                        },
                        new
                        {
                            Id = 88,
                            Answer = "Böter, rättsliga påföljder, förlorat förtroende från kunder och skada på företagets rykte",
                            IsCorrect = true,
                            QuestionId = 30
                        },
                        new
                        {
                            Id = 89,
                            Answer = "Ökad tillväxt och konkurrensfördelar",
                            IsCorrect = false,
                            QuestionId = 30
                        },
                        new
                        {
                            Id = 90,
                            Answer = "Större exponering för externa investerare",
                            IsCorrect = false,
                            QuestionId = 30
                        },
                        new
                        {
                            Id = 91,
                            Answer = "För att minska risken för dataintrång och bedrägerier",
                            IsCorrect = true,
                            QuestionId = 31
                        },
                        new
                        {
                            Id = 92,
                            Answer = "För att skydda företagets immateriella tillgångar och säkerställa kontinuitet i verksamheten",
                            IsCorrect = false,
                            QuestionId = 31
                        },
                        new
                        {
                            Id = 93,
                            Answer = "För att öka företagets skuldsättning",
                            IsCorrect = false,
                            QuestionId = 31
                        },
                        new
                        {
                            Id = 94,
                            Answer = "Implementera brandväggar och intrusionsskyddssystem",
                            IsCorrect = true,
                            QuestionId = 32
                        },
                        new
                        {
                            Id = 95,
                            Answer = "Använda osäker Wi-Fi-anslutning",
                            IsCorrect = false,
                            QuestionId = 32
                        },
                        new
                        {
                            Id = 96,
                            Answer = "Öppna e-postbilagor från okända avsändare",
                            IsCorrect = false,
                            QuestionId = 32
                        },
                        new
                        {
                            Id = 97,
                            Answer = "Medarbetarnas beteende och medvetenhet",
                            IsCorrect = true,
                            QuestionId = 33
                        },
                        new
                        {
                            Id = 98,
                            Answer = "Installation av antivirusprogramvara",
                            IsCorrect = false,
                            QuestionId = 33
                        },
                        new
                        {
                            Id = 99,
                            Answer = "Användning av svaga lösenord",
                            IsCorrect = false,
                            QuestionId = 33
                        },
                        new
                        {
                            Id = 100,
                            Answer = "För att skydda företagsnätverket mot obehörig åtkomst och skadlig kod",
                            IsCorrect = true,
                            QuestionId = 34
                        },
                        new
                        {
                            Id = 101,
                            Answer = "För att dela känslig information offentligt",
                            IsCorrect = false,
                            QuestionId = 34
                        },
                        new
                        {
                            Id = 102,
                            Answer = "För att öka nedladdningshastigheten",
                            IsCorrect = false,
                            QuestionId = 34
                        },
                        new
                        {
                            Id = 103,
                            Answer = "Konfigurera användarbehörigheter och behörighetsgrupper",
                            IsCorrect = true,
                            QuestionId = 35
                        },
                        new
                        {
                            Id = 104,
                            Answer = "Dela inloggningsuppgifter med andra användare",
                            IsCorrect = false,
                            QuestionId = 35
                        },
                        new
                        {
                            Id = 105,
                            Answer = "Använda samma lösenord för alla konton",
                            IsCorrect = false,
                            QuestionId = 35
                        },
                        new
                        {
                            Id = 106,
                            Answer = "Säkerhetskopiering och återställning av data",
                            IsCorrect = true,
                            QuestionId = 36
                        },
                        new
                        {
                            Id = 107,
                            Answer = "Användning av svaga lösenord",
                            IsCorrect = false,
                            QuestionId = 36
                        },
                        new
                        {
                            Id = 108,
                            Answer = "Delning av företagshemligheter på sociala medieplattformar",
                            IsCorrect = false,
                            QuestionId = 36
                        },
                        new
                        {
                            Id = 109,
                            Answer = "Kryptering av känslig information",
                            IsCorrect = true,
                            QuestionId = 37
                        },
                        new
                        {
                            Id = 110,
                            Answer = "Publicering av företagsuppgifter på offentliga webbplatser",
                            IsCorrect = false,
                            QuestionId = 37
                        },
                        new
                        {
                            Id = 111,
                            Answer = "Användning av standardlösenord för Wi-Fi-router",
                            IsCorrect = false,
                            QuestionId = 37
                        },
                        new
                        {
                            Id = 112,
                            Answer = "Ett ransomware-angrepp som krypterar företagets filer och kräver en lösensumma för att dekryptera dem",
                            IsCorrect = true,
                            QuestionId = 38
                        },
                        new
                        {
                            Id = 113,
                            Answer = "Ett säkerhetskopieringsverktyg för att säkerhetskopiera företagets data",
                            IsCorrect = false,
                            QuestionId = 38
                        },
                        new
                        {
                            Id = 114,
                            Answer = "Ett program för att skicka spam-e-post",
                            IsCorrect = false,
                            QuestionId = 38
                        },
                        new
                        {
                            Id = 115,
                            Answer = "Utbildning av anställda om cybersäkerhetsbästa praxis",
                            IsCorrect = true,
                            QuestionId = 39
                        },
                        new
                        {
                            Id = 116,
                            Answer = "Uppgradering av datorernas operativsystem",
                            IsCorrect = false,
                            QuestionId = 39
                        },
                        new
                        {
                            Id = 117,
                            Answer = "Delning av inloggningsuppgifter med okända parter",
                            IsCorrect = false,
                            QuestionId = 39
                        },
                        new
                        {
                            Id = 118,
                            Answer = "För att skydda företagets informationstillgångar, upprätthålla affärsfortsättning och följa lagliga krav",
                            IsCorrect = true,
                            QuestionId = 40
                        },
                        new
                        {
                            Id = 119,
                            Answer = "För att dela känslig information på osäkra nätverk",
                            IsCorrect = false,
                            QuestionId = 40
                        },
                        new
                        {
                            Id = 120,
                            Answer = "För att öka möjligheten till dataläckage",
                            IsCorrect = false,
                            QuestionId = 40
                        },
                        new
                        {
                            Id = 121,
                            Answer = "Konfigurera brandväggar med strikta regler och filtrera nätverkstrafik",
                            IsCorrect = true,
                            QuestionId = 41
                        },
                        new
                        {
                            Id = 122,
                            Answer = "Använda publika Wi-Fi-nätverk utan försiktighet",
                            IsCorrect = false,
                            QuestionId = 41
                        },
                        new
                        {
                            Id = 123,
                            Answer = "Dela lösenord med andra",
                            IsCorrect = false,
                            QuestionId = 41
                        },
                        new
                        {
                            Id = 124,
                            Answer = "Övervakar nätverkstrafik och upptäcker avvikande mönster",
                            IsCorrect = true,
                            QuestionId = 45
                        },
                        new
                        {
                            Id = 125,
                            Answer = "Ignorerar intrångsförsök",
                            IsCorrect = false,
                            QuestionId = 45
                        },
                        new
                        {
                            Id = 126,
                            Answer = "Blockerar all nätverkstrafik",
                            IsCorrect = false,
                            QuestionId = 45
                        },
                        new
                        {
                            Id = 127,
                            Answer = "Konfigurera brandväggar med rätt regler och filtrering av trafik",
                            IsCorrect = true,
                            QuestionId = 49
                        },
                        new
                        {
                            Id = 128,
                            Answer = "Använda publika Wi-Fi-nätverk utan försiktighet",
                            IsCorrect = false,
                            QuestionId = 49
                        },
                        new
                        {
                            Id = 129,
                            Answer = "Dela lösenord med andra",
                            IsCorrect = false,
                            QuestionId = 49
                        },
                        new
                        {
                            Id = 130,
                            Answer = "Verifiera identiteten hos kommunikationsparter och säkerställa att data inte har manipulerats under överföringen",
                            IsCorrect = true,
                            QuestionId = 53
                        },
                        new
                        {
                            Id = 131,
                            Answer = "Använda publika Wi-Fi-nätverk utan försiktighet",
                            IsCorrect = false,
                            QuestionId = 53
                        },
                        new
                        {
                            Id = 132,
                            Answer = "Dela lösenord med andra",
                            IsCorrect = false,
                            QuestionId = 53
                        },
                        new
                        {
                            Id = 133,
                            Answer = "Känsliga data som lösenord, kryptonycklar och digitala signaturer",
                            IsCorrect = true,
                            QuestionId = 57
                        },
                        new
                        {
                            Id = 134,
                            Answer = "Allmänna webbsidor",
                            IsCorrect = false,
                            QuestionId = 57
                        },
                        new
                        {
                            Id = 135,
                            Answer = "Offentliga nycklar",
                            IsCorrect = false,
                            QuestionId = 57
                        },
                        new
                        {
                            Id = 136,
                            Answer = "Övervakar nätverkstrafik och upptäcker avvikande mönster",
                            IsCorrect = true,
                            QuestionId = 42
                        },
                        new
                        {
                            Id = 137,
                            Answer = "Ignorerar intrångsförsök",
                            IsCorrect = false,
                            QuestionId = 42
                        },
                        new
                        {
                            Id = 138,
                            Answer = "Blockerar all nätverkstrafik",
                            IsCorrect = false,
                            QuestionId = 42
                        },
                        new
                        {
                            Id = 139,
                            Answer = "Verifiera identiteten hos kommunikationsparter och säkerställa att data inte har manipulerats under överföringen",
                            IsCorrect = true,
                            QuestionId = 46
                        },
                        new
                        {
                            Id = 140,
                            Answer = "Använda publika Wi-Fi-nätverk utan försiktighet",
                            IsCorrect = false,
                            QuestionId = 46
                        },
                        new
                        {
                            Id = 141,
                            Answer = "Dela lösenord med andra",
                            IsCorrect = false,
                            QuestionId = 46
                        },
                        new
                        {
                            Id = 142,
                            Answer = "Verifiera identiteten hos kommunikationsparter och säkerställa att data inte har manipulerats under överföringen",
                            IsCorrect = true,
                            QuestionId = 50
                        },
                        new
                        {
                            Id = 143,
                            Answer = "Använda publika Wi-Fi-nätverk utan försiktighet",
                            IsCorrect = false,
                            QuestionId = 50
                        },
                        new
                        {
                            Id = 144,
                            Answer = "Dela lösenord med andra",
                            IsCorrect = false,
                            QuestionId = 50
                        },
                        new
                        {
                            Id = 145,
                            Answer = "Verifiera identiteten hos kommunikationsparter och säkerställa att data inte har manipulerats under överföringen",
                            IsCorrect = true,
                            QuestionId = 54
                        },
                        new
                        {
                            Id = 146,
                            Answer = "Använda publika Wi-Fi-nätverk utan försiktighet",
                            IsCorrect = false,
                            QuestionId = 54
                        },
                        new
                        {
                            Id = 147,
                            Answer = "Dela lösenord med andra",
                            IsCorrect = false,
                            QuestionId = 54
                        },
                        new
                        {
                            Id = 148,
                            Answer = "Snabbare och mer effektiv för att kryptera stora mängder data",
                            IsCorrect = true,
                            QuestionId = 43
                        },
                        new
                        {
                            Id = 149,
                            Answer = "Mindre säker än asymmetrisk kryptering",
                            IsCorrect = false,
                            QuestionId = 43
                        },
                        new
                        {
                            Id = 150,
                            Answer = "Endast lämplig för säker kommunikation inom nätverk",
                            IsCorrect = false,
                            QuestionId = 43
                        },
                        new
                        {
                            Id = 151,
                            Answer = "Snabbare kryptering och avkryptering av filer jämfört med asymmetrisk kryptering",
                            IsCorrect = true,
                            QuestionId = 47
                        },
                        new
                        {
                            Id = 152,
                            Answer = "Mindre säker än asymmetrisk kryptering",
                            IsCorrect = false,
                            QuestionId = 47
                        },
                        new
                        {
                            Id = 153,
                            Answer = "Endast lämplig för kryptering av lösenord",
                            IsCorrect = false,
                            QuestionId = 47
                        },
                        new
                        {
                            Id = 154,
                            Answer = "Snabbare kryptering och avkryptering av filer jämfört med asymmetrisk kryptering",
                            IsCorrect = true,
                            QuestionId = 51
                        },
                        new
                        {
                            Id = 155,
                            Answer = "Mindre säker än asymmetrisk kryptering",
                            IsCorrect = false,
                            QuestionId = 51
                        },
                        new
                        {
                            Id = 156,
                            Answer = "Endast lämplig för kryptering av lösenord",
                            IsCorrect = false,
                            QuestionId = 51
                        },
                        new
                        {
                            Id = 157,
                            Answer = "Snabbare kryptering och avkryptering av filer jämfört med asymmetrisk kryptering",
                            IsCorrect = true,
                            QuestionId = 55
                        },
                        new
                        {
                            Id = 158,
                            Answer = "Mindre säker än asymmetrisk kryptering",
                            IsCorrect = false,
                            QuestionId = 55
                        },
                        new
                        {
                            Id = 159,
                            Answer = "Endast lämplig för kryptering av lösenord",
                            IsCorrect = false,
                            QuestionId = 55
                        });
                });

            modelBuilder.Entity("ValhallaVault.Data.Models.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Info = "Metoder för att skydda sig mot bedrägerier, inklusive att känna igen vanliga bedrägeriförsök, skydda personlig information och förstå hur man rapporterar bedrägliga aktiviteter. Denna kategori täcker olika aspekter av bedrägeriförebyggande, såsom skydd mot identitetsstöld, säkerhetspraxis på nätet och medvetenhet om finansiella bedrägerier. Genom att utbilda individer om potentiella hot och tillhandahålla strategier för att minska risker syftar denna kategori till att ge människor verktyg för att skydda sig från att bli offer för bedrägliga scheman och scams.",
                            Name = "Att Skydda Sig Mot Bedrägerier"
                        },
                        new
                        {
                            Id = 2,
                            Info = "Information och riktlinjer för att säkra företagsdata och nätverk mot cyberhot. Denna kategori omfattar olika aspekter av cybersäkerhet för företag, inklusive riskhantering, skydd mot skadlig programvara, medvetenhetsträning för anställda och efterlevnad av dataskyddsföreskrifter. Genom att tillhandahålla strategier och bästa praxis syftar denna kategori till att hjälpa företag att stärka sin cyberförsvar och minimera risken för dataintrång och ekonomisk skada.",
                            Name = "Cybersäkerhet för företag"
                        },
                        new
                        {
                            Id = 3,
                            Info = "Metoder för att förhindra och upptäcka spionage och attacker på internet, inklusive skydd av personlig information, igenkänning av vanliga cyberhot och rapportering av misstänkta aktiviteter. Denna kategori täcker olika aspekter av cyber- och spionageskydd, såsom säkerhetspraxis för nätverk, krypteringstekniker och förståelse för socialt ingenjörskap. Genom att öka medvetenheten och tillhandahålla strategier för att minska risker syftar denna kategori till att stärka användare för att skydda sig mot cyberattacker och spionagesyften.",
                            Name = "CyberSpionage"
                        });
                });

            modelBuilder.Entity("ValhallaVault.Data.Models.QuestionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubcategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Explanation = "Genom att implementera starka lösenord kan man förhindra obehörig åtkomst till personuppgifter.",
                            Question = "Vilka är några strategier för att säkra personuppgifter?",
                            SubcategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            Explanation = "Att aktivera tvåfaktorsautentisering är ett effektivt sätt att förhindra obehörig åtkomst till känslig information.",
                            Question = "Hur kan individer förhindra obehörig åtkomst till känslig information?",
                            SubcategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            Explanation = "Genom att kryptera data förhindras obehörig åtkomst och skyddar integriteten för personuppgifter.",
                            Question = "Varför är datakryptering viktigt för att skydda integriteten?",
                            SubcategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            Explanation = "Att använda säkra betalningsgatewayer är en effektiv åtgärd för att säkerställa datasäkerhet vid online-transaktioner.",
                            Question = "Vilka åtgärder kan vidtas för att säkerställa datasäkerhet vid online-transaktioner?",
                            SubcategoryId = 1
                        },
                        new
                        {
                            Id = 5,
                            Explanation = "Genom att granska integritetsinställningarna på sociala medieplattformar kan man identifiera potentiella risker för datas integritet.",
                            Question = "Hur identifierar man potentiella risker för datas integritet?",
                            SubcategoryId = 1
                        },
                        new
                        {
                            Id = 6,
                            Explanation = "Kreditövervakning är en tjänst som hjälper till att övervaka kreditrapporter och upptäcka eventuella bedrägliga aktiviteter. Det fungerar genom att regelbundet övervaka kreditrapporter och varna för avvikelser.",
                            Question = "Vad är kreditövervakning och hur fungerar det?",
                            SubcategoryId = 2
                        },
                        new
                        {
                            Id = 7,
                            Explanation = "En fördel med att använda kreditövervakningstjänster är att det möjliggör tidig upptäckt av identitetsstöld och bedrägerier på kreditrapporter.",
                            Question = "Vilka fördelar finns med att använda kreditövervakningstjänster?",
                            SubcategoryId = 2
                        },
                        new
                        {
                            Id = 8,
                            Explanation = "Genom att regelbundet kontrollera kreditrapporter kan individer upptäcka ovanliga eller misstänkta aktiviteter, vilket kan vara tecken på bedrägeri.",
                            Question = "Hur kan individer upptäcka bedrägliga aktiviteter på sina kreditrapporter?",
                            SubcategoryId = 2
                        },
                        new
                        {
                            Id = 9,
                            Explanation = "Om misstänksam aktivitet upptäcks på en kreditrapport bör individen omedelbart rapportera det till kreditbyråerna för vidare utredning.",
                            Question = "Vilka åtgärder bör vidtas om misstänksam aktivitet upptäcks på en kreditrapport?",
                            SubcategoryId = 2
                        },
                        new
                        {
                            Id = 10,
                            Explanation = "Ja, att använda identitetsstödskontroller och övervaka kontoutdrag kan vara alternativ till kreditövervakning för bedrägeriupptäckt.",
                            Question = "Finns det några alternativ till kreditövervakning för bedrägeriupptäckt?",
                            SubcategoryId = 2
                        },
                        new
                        {
                            Id = 11,
                            Explanation = "HTTPS-webbplatser använder kryptering för att säkra kommunikationen mellan webbläsaren och webbservern, vilket skyddar användares integritet och säkerhet vid surfning.",
                            Question = "Vad är HTTPS-webbplatser och varför är de viktiga för säker surfning?",
                            SubcategoryId = 3
                        },
                        new
                        {
                            Id = 12,
                            Explanation = "Genom att använda VPN-tjänster kan individer kryptera sin internettrafik och säkra sina data när de använder offentliga Wi-Fi-nätverk.",
                            Question = "Hur kan individer skydda sina data när de använder offentliga Wi-Fi-nätverk?",
                            SubcategoryId = 3
                        },
                        new
                        {
                            Id = 13,
                            Explanation = "Webbläsaruppdateringar är viktiga för att patcha säkerhetshål och sårbarheter, vilket minskar risken för attacker och säkerhetsintrång.",
                            Question = "Vilken roll spelar webbläsaruppdateringar för att upprätthålla nätverkssäkerheten?",
                            SubcategoryId = 3
                        },
                        new
                        {
                            Id = 14,
                            Explanation = "Vanliga nätverkssäkerhetshot inkluderar phishingattacker och skadlig kod. De kan undvikas genom att vara försiktig med länkar och bifogade filer samt genom att använda säkerhetsprogramvara.",
                            Question = "Vilka är några vanliga nätverkssäkerhetshot och hur kan de undvikas?",
                            SubcategoryId = 3
                        },
                        new
                        {
                            Id = 15,
                            Explanation = "Genom att kontrollera om webbplatsen använder HTTPS och har giltiga SSL-certifikat kan användare bedöma om det är säkert att genomföra online-transaktioner på webbplatsen.",
                            Question = "Hur kan användare identifiera om en webbplats är säker för online-transaktioner?",
                            SubcategoryId = 3
                        },
                        new
                        {
                            Id = 16,
                            Explanation = "Phishing-e-postmeddelanden är bedrägliga meddelanden som utger sig för att vara från pålitliga källor för att lura mottagarna att lämna ut personlig eller känslig information. De fungerar genom att locka mottagaren att klicka på skadliga länkar eller bifogade filer.",
                            Question = "Vad är phishing-e-postmeddelanden och hur fungerar de?",
                            SubcategoryId = 4
                        },
                        new
                        {
                            Id = 17,
                            Explanation = "Genom att vara uppmärksam på varningsflaggor, såsom oegentliga begäranden om känslig information eller brådskande åtgärder, kan individer undvika att bli lurade av phishing-bedrägerier.",
                            Question = "Hur kan individer känna igen och undvika att bli lurade av phishing-bedrägerier?",
                            SubcategoryId = 4
                        },
                        new
                        {
                            Id = 18,
                            Explanation = "Misspelled avsändarens e-postadress och ovanliga begäranden om känslig information kan vara indikatorer på ett misstänkt e-postmeddelande.",
                            Question = "Vilka är några indikatorer på ett misstänkt e-postmeddelande?",
                            SubcategoryId = 4
                        },
                        new
                        {
                            Id = 19,
                            Explanation = "Att verifiera avsändarens identitet kan förhindra att svara på phishing-e-postmeddelanden och därigenom undvika att lämna ut personlig eller känslig information till bedragare.",
                            Question = "Varför är det viktigt att verifiera avsändarens identitet innan man svarar på e-postmeddelanden?",
                            SubcategoryId = 4
                        },
                        new
                        {
                            Id = 20,
                            Explanation = "Om en individ misstänker att de har fått ett phishing-e-postmeddelande bör de rapportera det till lämpliga myndigheter eller organisationer för att varna andra och förhindra ytterligare bedrägerier.",
                            Question = "Vilka åtgärder bör vidtas om en individ misstänker att de har fått ett phishing-e-postmeddelande?",
                            SubcategoryId = 4
                        },
                        new
                        {
                            Id = 21,
                            Explanation = "En typisk riskbedömningsprocess för företag inkluderar identifiering av risker, bedömning av riskernas sannolikhet och påverkan, och utveckling av riskhanteringsstrategier.",
                            Question = "Vilka steg ingår i en typisk riskbedömningsprocess för företag?",
                            SubcategoryId = 5
                        },
                        new
                        {
                            Id = 22,
                            Explanation = "Syftet med en riskhanteringsplan inom cybersäkerhet är att definiera företagets strategi för att hantera och minimera risker för dataintrång och förlust av företagsinformation.",
                            Question = "Vad är syftet med en riskhanteringsplan inom cybersäkerhet?",
                            SubcategoryId = 5
                        },
                        new
                        {
                            Id = 23,
                            Explanation = "Företag kan förebygga spridning av skadlig programvara genom att använda uppdaterad antivirusprogramvara, implementera brandväggar och utbilda personalen om säker surfning och e-posthantering.",
                            Question = "Hur kan företag förebygga spridning av skadlig programvara på sina nätverk?",
                            SubcategoryId = 6
                        },
                        new
                        {
                            Id = 24,
                            Explanation = "Ransomware är skadlig programvara som krypterar filer på offrets enhet och kräver betalning för att låsa upp dem. Företag kan skydda sig mot ransomware genom att säkerhetskopiera data regelbundet och undvika att klicka på misstänkta länkar eller öppna bifogade filer i e-postmeddelanden.",
                            Question = "Vad är ransomware och hur kan företag skydda sig mot det?",
                            SubcategoryId = 6
                        },
                        new
                        {
                            Id = 25,
                            Explanation = "Det är viktigt att företagsanställda är medvetna om cybersäkerhetsrisker för att minska risken för dataintrång och bedrägerier. Genom att känna igen potentiella hot och följa bästa praxis kan anställda bidra till att skydda företagets data och nätverk.",
                            Question = "Varför är det viktigt att företagsanställda är medvetna om cybersäkerhetsrisker?",
                            SubcategoryId = 7
                        },
                        new
                        {
                            Id = 26,
                            Explanation = "Anställda kan utsättas för risker som phishingattacker via e-post, skadlig programvara via nedladdningar, eller oavsiktlig dataexponering genom bristande säkerhetsmedvetenhet.",
                            Question = "Vilka typer av cybersäkerhetsrisker kan anställda utsättas för?",
                            SubcategoryId = 7
                        },
                        new
                        {
                            Id = 27,
                            Explanation = "Företag kan genomföra cybersäkerhetsträning, skicka ut information om aktuella hot och bästa praxis regelbundet, och uppmuntra anställda att rapportera misstänkta aktiviteter.",
                            Question = "Vilka åtgärder kan företag vidta för att öka medvetenheten om cybersäkerhet bland sina anställda?",
                            SubcategoryId = 7
                        },
                        new
                        {
                            Id = 28,
                            Explanation = "Lagar som GDPR (Dataskyddsförordningen) och CCPA (California Consumer Privacy Act) styr hanteringen av företagsdata och personlig information för att skydda användares integritet och reglera företags insamling och användning av personlig information.",
                            Question = "Vilka lagar och regler styr hanteringen av företagsdata och personlig information?",
                            SubcategoryId = 8
                        },
                        new
                        {
                            Id = 29,
                            Explanation = "Efterlevnad av dataskyddsföreskrifter för företag innebär att de måste följa specifika regler och riktlinjer för att skydda användares personlig information, rapportera dataintrång och upprätthålla säkerhetsåtgärder för att förhindra obehörig åtkomst.",
                            Question = "Vad innebär efterlevnad av dataskyddsföreskrifter för företag?",
                            SubcategoryId = 8
                        },
                        new
                        {
                            Id = 30,
                            Explanation = "Konsekvenserna av att inte följa dataskyddsföreskrifter för företag kan inkludera böter, rättsliga påföljder, förlorat förtroende från kunder och skada på företagets rykte.",
                            Question = "Vad är konsekvenserna av att inte följa dataskyddsföreskrifter för företag?",
                            SubcategoryId = 8
                        },
                        new
                        {
                            Id = 31,
                            Explanation = "Företag kan säkra sina nätverk och system mot skadlig programvara genom att använda brandväggar, antivirusprogram, intrusion detection systems (IDS), och genom att implementera strikta behörighetsåtgärder och uppdatera programvara regelbundet.",
                            Question = "Hur kan företag säkra sina nätverk och system mot skadlig programvara?",
                            SubcategoryId = 6
                        },
                        new
                        {
                            Id = 32,
                            Explanation = "En DDOS (Distributed Denial of Service) attack är när en angripare översvämmar en server eller nätverk med en stor mängd trafik för att överbelasta det och göra det otillgängligt för legitima användare. Företag kan skydda sig mot DDOS-attacker genom att använda DDOS-skyddstjänster och konfigurera nätverksutrustning för att filtrera ut skadlig trafik.",
                            Question = "Vad är en DDOS-attack och hur kan företag skydda sig mot det?",
                            SubcategoryId = 6
                        },
                        new
                        {
                            Id = 33,
                            Explanation = "En säkerhetspolicy för företaget är en uppsättning riktlinjer och förfaranden som definierar hur företaget skyddar sina data och informationssystem från interna och externa hot. Det är viktigt eftersom det skapar en ram för att etablera och upprätthålla säkerhetsåtgärder och säkerställer efterlevnad av lagar och regler.",
                            Question = "Vad är en säkerhetspolicy för företaget och varför är det viktigt?",
                            SubcategoryId = 8
                        },
                        new
                        {
                            Id = 34,
                            Explanation = "Social ingenjörskonst är när en angripare manipulerar människor för att få tillgång till känslig information eller system. Företag kan skydda sig mot social ingenjörskonst genom att utbilda anställda om vanliga taktiker, implementera strikta autentiseringsåtgärder och uppmuntra en kultur av säkerhet och skepticism.",
                            Question = "Vad är social ingenjörskonst och hur kan företag skydda sig mot det?",
                            SubcategoryId = 7
                        },
                        new
                        {
                            Id = 35,
                            Explanation = "Företag kan säkra sina interna system och data från insiderhot genom att tillämpa principen om minsta privilegium, övervaka användaraktivitet, använda åtkomstkontroller och genomföra regelbundna säkerhetsrevisioner.",
                            Question = "Hur kan företag säkra sina interna system och data från insiderhot?",
                            SubcategoryId = 6
                        },
                        new
                        {
                            Id = 36,
                            Explanation = "Det är viktigt för företag att säkerhetskopiera sina data regelbundet eftersom det minskar risken för permanent dataförlust vid händelser som ransomware-attacker, systemfel eller naturkatastrofer.",
                            Question = "Varför är det viktigt för företag att säkerhetskopiera sina data regelbundet?",
                            SubcategoryId = 6
                        },
                        new
                        {
                            Id = 37,
                            Explanation = "Företag kan övervaka sina nätverk med hjälp av intrångsdetektionssystem (IDS), intrångsförebyggande system (IPS) och säkerhetsinformation- och händelsehantering (SIEM)-verktyg för att upptäcka och svara på misstänkta aktiviteter.",
                            Question = "Hur kan företag övervaka sina nätverk för att upptäcka potentiella intrång?",
                            SubcategoryId = 5
                        },
                        new
                        {
                            Id = 38,
                            Explanation = "Fördelarna med att implementera en säkerhetsmedvetenhetskultur inom företaget inkluderar minskad risk för dataintrång och förluster, ökad upptäckt av hot och incidenter och förbättrad efterlevnad av säkerhetspolicyer och föreskrifter.",
                            Question = "Vilka är fördelarna med att implementera en säkerhetsmedvetenhetskultur inom företaget?",
                            SubcategoryId = 7
                        },
                        new
                        {
                            Id = 39,
                            Explanation = "Företag kan utveckla en effektiv incidenthanteringsprocess för cybersäkerhet genom att etablera en incidentresponsplan, tilldela roller och ansvarsområden, och genomföra regelbundna övningar och utvärderingar för att förbättra responsförmågan.",
                            Question = "Hur kan företag utveckla en effektiv incidenthanteringsprocess för cybersäkerhet?",
                            SubcategoryId = 5
                        },
                        new
                        {
                            Id = 40,
                            Explanation = "Fördelarna med att använda säkerhetsinformation- och händelsehantering (SIEM)-verktyg inkluderar realtidsövervakning av nätverk och system, snabb identifiering och respons på incidenter, och möjligheten att analysera och rapportera om säkerhetsdata för att förbättra framtida skyddsstrategier.",
                            Question = "Vad är fördelarna med att använda säkerhetsinformation- och händelsehantering (SIEM)-verktyg?",
                            SubcategoryId = 5
                        },
                        new
                        {
                            Id = 41,
                            Explanation = "Genom att konfigurera brandväggar med strikta regler och filtrera nätverkstrafik kan man förhindra obehöriga användare från att komma åt nätverket.",
                            Question = "Vilken typ av åtgärder kan vidtas för att förhindra obehörig åtkomst till nätverk?",
                            SubcategoryId = 9
                        },
                        new
                        {
                            Id = 45,
                            Explanation = "Intrångsdetektionssystem övervakar nätverkstrafik och upptäcker avvikande mönster som kan indikera en cyberattack, vilket gör det möjligt för administratörer att vidta åtgärder för att förhindra intrång.",
                            Question = "Hur fungerar intrångsdetektionssystem för att skydda nätverk?",
                            SubcategoryId = 9
                        },
                        new
                        {
                            Id = 49,
                            Explanation = "Genom att konfigurera brandväggar med rätt regler och filtrering av trafik kan man förhindra obehörig åtkomst och skydda mot skadlig programvara.",
                            Question = "Vilka åtgärder kan vidtas för att skydda nätverk genom brandväggskonfiguration?",
                            SubcategoryId = 9
                        },
                        new
                        {
                            Id = 53,
                            Explanation = "Digitala certifikat används för att verifiera identiteten hos kommunikationsparter och säkerställa att data inte har manipulerats under överföringen, vilket garanterar en säker och pålitlig nätverkskommunikation.",
                            Question = "Hur fungerar digitala certifikat för att säkra nätverkskommunikationen?",
                            SubcategoryId = 9
                        },
                        new
                        {
                            Id = 57,
                            Explanation = "Asymmetrisk kryptering används vanligtvis för att kryptera känsliga data som lösenord, kryptonycklar och digitala signaturer för säker kommunikation över nätverk.",
                            Question = "Vilken typ av data kan krypteras med asymmetrisk kryptering?",
                            SubcategoryId = 9
                        },
                        new
                        {
                            Id = 42,
                            Explanation = "Intrångsdetektionssystem övervakar nätverkstrafik och upptäcker avvikande mönster som kan indikera en cyberattack, vilket möjliggör snabb identifiering och hantering av intrångsförsök.",
                            Question = "Hur kan man identifiera och hantera intrång i nätverket med intrångsdetektionssystem?",
                            SubcategoryId = 10
                        },
                        new
                        {
                            Id = 46,
                            Explanation = "Digitala certifikat används för att verifiera identiteten hos kommunikationsparter och säkerställa att data inte har manipulerats under överföringen, vilket garanterar en säker och pålitlig nätverkskommunikation.",
                            Question = "Hur fungerar digitala certifikat för att säkra nätverkskommunikationen?",
                            SubcategoryId = 10
                        },
                        new
                        {
                            Id = 50,
                            Explanation = "Digitala certifikat används för att verifiera identiteten hos kommunikationsparter och säkerställa att data inte har manipulerats under överföringen, vilket garanterar en säker och pålitlig nätverkskommunikation.",
                            Question = "Hur fungerar digitala certifikat för att säkra nätverkskommunikationen?",
                            SubcategoryId = 10
                        },
                        new
                        {
                            Id = 54,
                            Explanation = "Digitala certifikat används för att verifiera identiteten hos kommunikationsparter och säkerställa att data inte har manipulerats under överföringen, vilket garanterar en säker och pålitlig nätverkskommunikation.",
                            Question = "Hur fungerar digitala certifikat för att säkra nätverkskommunikationen?",
                            SubcategoryId = 10
                        },
                        new
                        {
                            Id = 58,
                            Explanation = "Digitala certifikat används för att verifiera identiteten hos kommunikationsparter och säkerställa att data inte har manipulerats under överföringen, vilket garanterar en säker och pålitlig nätverkskommunikation.",
                            Question = "Hur fungerar digitala certifikat för att säkra nätverkskommunikationen?",
                            SubcategoryId = 10
                        },
                        new
                        {
                            Id = 43,
                            Explanation = "Symmetrisk kryptering är snabbare och mer effektiv för att kryptera stora mängder data jämfört med asymmetrisk kryptering, vilket gör det lämpligt för säker kommunikation inom nätverk.",
                            Question = "Vad är fördelarna med symmetrisk kryptering jämfört med asymmetrisk kryptering?",
                            SubcategoryId = 11
                        },
                        new
                        {
                            Id = 47,
                            Explanation = "Symmetrisk kryptering erbjuder snabbare kryptering och avkryptering av filer jämfört med asymmetrisk kryptering, vilket gör det lämpligt för att säkra lagrade data.",
                            Question = "Vad är fördelarna med att använda symmetrisk kryptering för filkryptering?",
                            SubcategoryId = 11
                        },
                        new
                        {
                            Id = 51,
                            Explanation = "Symmetrisk kryptering erbjuder snabbare kryptering och avkryptering av filer jämfört med asymmetrisk kryptering, vilket gör det lämpligt för att säkra lagrade data.",
                            Question = "Vad är fördelarna med att använda symmetrisk kryptering för filkryptering?",
                            SubcategoryId = 11
                        },
                        new
                        {
                            Id = 55,
                            Explanation = "Symmetrisk kryptering erbjuder snabbare kryptering och avkryptering av filer jämfört med asymmetrisk kryptering, vilket gör det lämpligt för att säkra lagrade data.",
                            Question = "Vad är fördelarna med att använda symmetrisk kryptering för filkryptering?",
                            SubcategoryId = 11
                        },
                        new
                        {
                            Id = 59,
                            Explanation = "Symmetrisk kryptering erbjuder snabbare kryptering och avkryptering av filer jämfört med asymmetrisk kryptering, vilket gör det lämpligt för att säkra lagrade data.",
                            Question = "Vad är fördelarna med att använda symmetrisk kryptering för filkryptering?",
                            SubcategoryId = 11
                        });
                });

            modelBuilder.Entity("ValhallaVault.Data.Models.SegmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Segments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Info = "Strategier och metoder för att förhindra identitetsstöld, inklusive att säkra personlig information och känna igen varningssignaler för potentiella bedrägeriförsök.",
                            Name = "Skydd mot Identitetsstöld"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Info = "Bästa praxis för att upprätthålla säkerhet på nätet, såsom att använda starka lösenord, aktivera tvåfaktorsautentisering och undvika phishingförsök.",
                            Name = "Säkerhetspraxis på Nätet"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Info = "Metoder och processer för att identifiera, bedöma och hantera risker relaterade till cybersäkerhet inom företagsmiljöer.",
                            Name = "Riskhantering"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Info = "Strategier och verktyg för att skydda företagsnätverk och system mot skadlig programvara, inklusive virus, spionprogram och ransomware.",
                            Name = "Skydd mot Skadlig Programvara"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Info = "Praktiska åtgärder för att säkra nätverk mot cyberattacker, inklusive brandväggskonfiguration, intrångsdetektionssystem och nätverkssegmentering.",
                            Name = "Nätverkssäkerhet"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Info = "Metoder för att använda kryptering för att skydda data mot obehörig åtkomst och avlyssning, inklusive symmetrisk och asymmetrisk kryptering samt säkra kommunikationsprotokoll.",
                            Name = "Krypteringstekniker"
                        });
                });

            modelBuilder.Entity("ValhallaVault.Data.Models.SubcategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SegmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SegmentId");

                    b.ToTable("Subcategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Info = "Riktlinjer för att skydda personuppgifter och förhindra obehörig åtkomst till känslig information.",
                            Name = "Tips för Dataskydd",
                            SegmentId = 1
                        },
                        new
                        {
                            Id = 2,
                            Info = "Information om kreditövervakningstjänster och hur de kan hjälpa individer att upptäcka bedrägliga aktiviteter relaterade till deras kreditrapporter.",
                            Name = "Kreditövervakningstjänster",
                            SegmentId = 1
                        },
                        new
                        {
                            Id = 3,
                            Info = "Tips för att säkert surfa på internet, såsom att använda HTTPS-webbplatser, undvika offentliga Wi-Fi-nätverk och regelbundet uppdatera webbläsare.",
                            Name = "Säkra Surfningspraxis",
                            SegmentId = 2
                        },
                        new
                        {
                            Id = 4,
                            Info = "Metoder för att förbättra e-postsäkerheten, inklusive att känna igen phishing-e-postmeddelanden, verifiera avsändarens identitet och använda e-postkryptering.",
                            Name = "E-postsäkerhetsåtgärder",
                            SegmentId = 2
                        },
                        new
                        {
                            Id = 5,
                            Info = "Processen att identifiera och bedöma potentiella risker för företagsdata och informationssystem för att fatta informerade beslut om riskhantering.",
                            Name = "Riskbedömning",
                            SegmentId = 3
                        },
                        new
                        {
                            Id = 6,
                            Info = "Metoder och verktyg för att förebygga, upptäcka och ta bort skadlig programvara från företagsnätverk och enheter.",
                            Name = "Malware Skydd",
                            SegmentId = 4
                        },
                        new
                        {
                            Id = 7,
                            Info = "Utbildning och träningsprogram för att öka medvetenheten hos företagsanställda om cybersäkerhetsrisker och bästa praxis för att minska riskerna.",
                            Name = "Anställd Medvetenhet",
                            SegmentId = 3
                        },
                        new
                        {
                            Id = 8,
                            Info = "Policyer och förfaranden som företag implementerar för att efterleva dataskyddsföreskrifter och säkra känslig företagsinformation.",
                            Name = "Företags Dataskyddsregler",
                            SegmentId = 4
                        },
                        new
                        {
                            Id = 9,
                            Info = "Inställningar och regler för att konfigurera brandväggar och filtrera nätverkstrafik för att förhindra obehörig åtkomst och skydda mot skadlig programvara.",
                            Name = "Brandväggskonfiguration",
                            SegmentId = 5
                        },
                        new
                        {
                            Id = 10,
                            Info = "Tekniker för att övervaka nätverkstrafik och identifiera avvikande beteenden som kan indikera en cyberattack, samt implementering av åtgärder för att förhindra intrång.",
                            Name = "Intrångsdetektionssystem",
                            SegmentId = 5
                        },
                        new
                        {
                            Id = 11,
                            Info = "En krypteringsmetod där samma nyckel används för både kryptering och dekryptering av data, och implementeringen av algoritmer som AES för att säkra kommunikation.",
                            Name = "Symmetrisk Kryptering",
                            SegmentId = 6
                        },
                        new
                        {
                            Id = 12,
                            Info = "En krypteringsmetod där olika nycklar används för kryptering och dekryptering av data, samt användningen av RSA-algoritmen för att säkra överföring av kryptonycklar.",
                            Name = "Asymmetrisk Kryptering",
                            SegmentId = 6
                        });
                });

            modelBuilder.Entity("ValhallaVault.Data.Models.UserQuestionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("UserQuestions");
                });

            modelBuilder.Entity("ValhallaVault.Data.Models.AnswerModel", b =>
                {
                    b.HasOne("ValhallaVault.Data.Models.QuestionModel", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ValhallaVault.Data.Models.QuestionModel", b =>
                {
                    b.HasOne("ValhallaVault.Data.Models.SubcategoryModel", "Subcategory")
                        .WithMany("Questions")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("ValhallaVault.Data.Models.SegmentModel", b =>
                {
                    b.HasOne("ValhallaVault.Data.Models.CategoryModel", "Category")
                        .WithMany("Segments")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ValhallaVault.Data.Models.SubcategoryModel", b =>
                {
                    b.HasOne("ValhallaVault.Data.Models.SegmentModel", "Segment")
                        .WithMany("Subcategories")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("ValhallaVault.Data.Models.UserQuestionModel", b =>
                {
                    b.HasOne("ValhallaVault.Data.Models.QuestionModel", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ValhallaVault.Data.Models.CategoryModel", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("ValhallaVault.Data.Models.QuestionModel", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("ValhallaVault.Data.Models.SegmentModel", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("ValhallaVault.Data.Models.SubcategoryModel", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
